import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import NavbarwithSearch from '@/components/NavbarwithSearch'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const isAuthenticated = false
  return (
    <html lang="en">
      <body className={inter.className}>
        {isAuthenticated ? <NavbarwithSearch /> : <Navbar />}
        {children}
        </body>
    </html>
  )
}
